name: abcd
on: 
  push: 
    branches: [ main ]

jobs: 
  exec:
    runs-on: ubuntu-latest
    steps:
      - name: saumya
        uses: actions/checkout@v2

      - name: setup python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"

      - name: tripathi
        run: python tester.py #echo git diff --name-only --diff-filter=ACMRT 