name: abcd
on: 
  push: 
    branches: [ main ]

jobs: 
  exec:
    runs-on: ubuntu-latest
    steps:
      - name: saumya
        uses: actions/checkout@v2


      - name: tripathi
        run: echo "Hello ppl"